const action = ['Action', 'First-Person', 'Military', 'War', 'Moddable', 'Violent', 'Adventure', 'Family Friendly', 'Local Co-Op', 'Early Access', 'Choices Matter', 'Co-op Campaign', 'Party Game', 'Party', 'Action-Adventure', 'Crime', 'America', 'Gun Customization', 'Third-Person Shooter', 'Survival', 'Third Person', 'Tower Defense', 'World War II', 'Cold War', 'Perma Death', 'Life Sim', 'Cartoony', 'Quick-Time Events', 'Action Roguelike', 'Detective', 'Football (American)', 'Creature Collector', 'Deckbuilding', 'Roguelite', 'Real-Time', 'TrackIR', 'Alternate History', 'Western', 'Character Action Game', 'Political', 'Trains', 'Action RTS', 'RPGMaker', 'Education', 'Collectathon', 'Roguevania', 'Social Deduction', 'Faith', 'Politics', 'Political Sim', '6DOF', 'Minimalist', 'Design & Illustration', 'Conspiracy', 'Underground', 'Photo Editing', 'Game Development', 'Voice Control'];

const rpg = ['FPS', 'PvP', 'Cyberpunk', 'RPG', 'Action RPG', 'PvE', 'CRPG', 'Zombies', 'Remake', 'Loot', 'Arcade', '2.5D', 'Steampunk', 'MOBA', 'RTS', 'VR', 'Swordplay', 'Puzzle', 'JRPG', 'Dragons', 'Ninja', 'Assassin', 'MMORPG', 'Mod', '2D', 'Dungeon Crawler', 'Musou', 'Epic', 'Roguelike Deckbuilder', 'Roguelike', 'Strategy RPG', 'Tactical RPG', '4X', 'Wargame', 'NSFW', 'God Game', 'Sniper', 'Solitaire', 'FMV', 'World War I', 'LEGO', 'Word Game', 'Pinball', 'Reboot', 'Otome', 'Hobby Sim', 'Mahjong'];

const strategy = ['Strategy', 'Stealth', 'Resource Management', 'Naval', 'Platformer', 'Economy', 'Open World Survival Craft', 'Capitalism', 'Sexual Content', 'Point & Click', 'Grand Strategy', 'Diplomacy', 'Time Travel', 'Real Time Tactics', 'Games Workshop', 'Foreign', 'Level Editor', 'Time Management', 'Software', 'Benchmark'];

const casual = ['Nudity', 'Casual', 'Cute', 'Female Protagonist', 'Relaxing', 'Beautiful', 'Colorful', 'Choose Your Own Adventure', 'Escape Room', 'Surreal', 'Short', 'Cozy', 'Retro', 'Wholesome', 'Memes', 'Shop Keeper'];

const simulation = ['Competitive', 'Team-Based', 'Tactical', 'Online Co-Op', 'Co-op', 'Difficult', 'Trading', 'Realistic', 'Fast-Paced', 'Futuristic', 'Mature', 'Atmospheric', 'Exploration', 'Character Customization', 'Controller', 'Simulation', 'Turn-Based Combat', 'Romance', 'Class-Based', 'Fighting', 'Physics', 'Cinematic', 'Space', 'Lore-Rich', 'Souls-like', 'Multiple Endings', 'Modern', 'Flight', 'Historical', 'Emotional', 'Management', 'Building', 'Nature', 'Base Building', 'Post-apocalyptic', 'Destruction', 'Hunting', 'Hack and Slash', 'Dating Sim', 'Farming Sim', 'Agriculture', 'Illuminati', 'Crafting', 'Real-Time with Pause', 'Underwater', 'Cooking', 'Procedural Generation', 'Medieval', 'Supernatural', 'Investigation', 'Turn-Based Tactics', 'Fishing', 'Mining', 'Inventory Management', 'Isometric', 'Stylized', 'Visual Novel', 'Driving', 'Walking Simulator', 'Turn-Based', 'Turn-Based Strategy', 'Hand-drawn', 'Experimental', 'Transportation', 'Hacking', 'Text-Based', 'Science', 'Nonlinear', 'Extraction Shooter', 'Conversation', 'Linear', 'Mythology', 'Automation', '3D Vision', 'Artificial Intelligence', 'Animation & Modeling', 'Psychological', 'Logic', 'Hidden Object', 'Medical Sim', 'Dynamic Narration', 'Snowboarding', 'Precision Platformer', 'Tutorial', 'Music-Based Procedural Generation', 'Unforgiving', 'Addictive', 'Touch-Friendly', 'Farming', 'Job Simulator', 'Transhumanism', 'Narration', 'Immersive', 'Interactive Fiction', 'Grid-Based Movement', 'Programming', 'Narrative', 'Mouse only', 'Abstract', 'Utilities', 'Spaceships', 'Well-Written', 'Submarine', 'On-Rails Shooter', 'Time Manipulation', 'Lemmings', 'Philosophical', 'Based On A Novel', 'Software Training', 'Mars', 'Skating', 'Experience', 'Hardware', 'Electronic', 'Typing', 'Traditional Roguelike', 'Intentionally Awkward Controls', 'Ambient', 'Coding', 'Audio Production', 'Tile-Matching', 'Spelling'];

const indie = ['Great Soundtrack', 'Indie', 'Rhythm', 'Soundtrack', 'Top-Down', 'Colony Sim', 'LGBTQ+', '1980s', 'Cult Classic', 'Music', 'Rock Music', 'Psychedelic', 'Crowdfunded', 'Electronic Music', 'Instrumental Music'];

const horror = ['Sci-fi', 'Story Rich', 'Fantasy', 'Dark Fantasy', 'Funny', 'Heist', 'Dark Humor', '"Shoot Em Up"', 'Horror', 'Survival Horror', 'Dark', 'Gore', 'Psychological Horror', 'Blood', 'Gothic', 'Anime', 'Comedy', 'Cartoon', 'Magic', 'Drama', 'Demons', 'Mystery', 'Thriller', 'Lovecraftian', 'Hentai', 'Superhero', 'Comic Book', 'Aliens', 'Cats', 'Dystopian', 'Dinosaurs', 'Sequel', '"1990s"', 'Silent Protagonist', 'Side Scroller', 'Noir', 'Dark Comedy', '"Beat em up"', 'Vampire', 'Nostalgia', 'Rome', 'Bullet Hell', 'Villain Protagonist', 'Snow', 'Idler', 'Bullet Time', 'Satire', 'Dog', 'Werewolves', 'Episodic', 'Trivia', 'Mystery Dungeon', 'Parody', 'Jump Scare', 'Boss Rush', 'Sokoban', 'Movie', 'Birds', 'Fox'];

const raing = ['Sailing', 'Horses', 'Automobile Sim', 'Racing', 'Classic', 'ATV', 'Offroad', 'Motocross', 'Motorbike', 'Bikes', 'Wrestling', 'Auto Battler', 'Combat Racing', 'Cycling', 'BMX', 'Baseball', 'Skateboarding', 'Bowling'];

const sport = ['eSports', 'Open World', 'Sports', 'Football (Soccer)', 'Martial Arts', 'City Builder', 'Parkour', 'Basketball', 'Skiing', 'Arena Shooter', 'Old School', 'Golf', 'Jet', 'Mini Golf', 'Boxing', 'Archery', 'Tennis', 'Volleyball', 'Rugby', 'Pool', 'Cricket', 'Hockey', 'Snooker'];

const multiplayer = ['Shooter', 'Multiplayer', 'Singleplayer', 'Immersive Sim', '3D', 'Local Multiplayer', 'Dungeons & Dragons', 'Combat', '3D Fighter', '4 Player Local', 'Space Sim', 'Free to Play', 'Battle Royale', 'Hero Shooter', '2D Fighter', 'Replay Value', 'Vehicular Combat', 'Tanks', 'Naval Combat', 'Massively Multiplayer', 'Pirates', 'Split Screen', 'Puzzle Platformer', '3D Platformer', 'Minigames', 'Sandbox', 'Looter Shooter', 'Robots', 'Mechs', 'Party-Based RPG', 'Spectacle fighter', 'Card Game', 'Trading Card Game', 'Card Battler', 'Pixel Graphics', 'Metroidvania', 'Voxel', 'Asynchronous Multiplayer', 'Hex Grid', 'Warhammer 40K', '2D Platformer', 'Kickstarter', 'Board Game', 'Tabletop', 'Top-Down Shooter', 'Score Attack', 'Clicker', 'Runner', 'Vikings', 'Gambling', 'Gaming', 'Twin Stick Shooter', 'Asymmetric VR', 'GameMaker', 'Time Attack', 'Match 3', 'Outbreak Sim', 'Chess', '360 Video'];


const tag = [action, rpg, strategy, casual, simulation, indie, horror, raing, sport, multiplayer]

export default tag;